# Generated by Django 4.1 on 2022-10-24 20:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for role', primary_key=True, serialize=False)),
                ('role_name', models.CharField(help_text='Enter role name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for stock', primary_key=True, serialize=False)),
                ('stock_name', models.CharField(help_text='Enter the stock name', max_length=20)),
                ('stock_ticker', models.CharField(help_text='Enter the stock ticker', max_length=20)),
                ('stock_quantity', models.CharField(help_text='Enter the stock quantity', max_length=20)),
                ('stock_active_quantity', models.CharField(help_text='Enter the stock active quantity', max_length=20)),
                ('stock_day_percentage', models.CharField(help_text='Enter the stock day percentage', max_length=20)),
                ('stock_highest_price', models.CharField(help_text='Enter the stock highest price', max_length=20)),
                ('stock_lowest_price', models.CharField(help_text='Enter the stock lowest price', max_length=20)),
                ('stock_open_price', models.CharField(help_text='Enter the stock open price', max_length=20)),
                ('stock_date', models.DateField(help_text='Enter the stock date')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for User', primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(help_text='Enter user first name', max_length=50)),
                ('user_last_name', models.CharField(help_text='Enter user last name', max_length=20)),
                ('user_email', models.EmailField(help_text='Enter user Email Address', max_length=254)),
                ('role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.role')),
                ('stock_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Watch_List',
            fields=[
                ('watchlist_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for watchlist', primary_key=True, serialize=False)),
                ('user_watchlist_name', models.CharField(help_text='Enter the watchlist name', max_length=50)),
                ('stock_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.stock')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.users')),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('threshold_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for threshold', primary_key=True, serialize=False)),
                ('threshold_percentage_change', models.CharField(help_text='Enter the stock threshold percentage change content', max_length=500)),
                ('threshold_price_change', models.CharField(help_text='Enter the stock threshold price change content', max_length=500)),
                ('stock_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks_list',
            fields=[
                ('stocks_list_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Stock List', primary_key=True, serialize=False)),
                ('stock_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.stock')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.users'),
        ),
        migrations.AddField(
            model_name='stock',
            name='watchlist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.watch_list'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for profile', primary_key=True, serialize=False)),
                ('profile_street', models.TextField(help_text='Enter profile street name', max_length=50)),
                ('profile_city', models.CharField(help_text='Enter profile city name', max_length=20)),
                ('profile_state', models.CharField(help_text='Enter profile state name', max_length=20)),
                ('profile_zipcode', models.CharField(help_text='Enter profile zipcode name', max_length=10)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.users')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('preference_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for preference', primary_key=True, serialize=False)),
                ('stock_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.stock')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.users')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('news_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the news', primary_key=True, serialize=False)),
                ('news_title', models.CharField(help_text='Enter the stock news title', max_length=50)),
                ('news_content', models.TextField(help_text='Enter the stock news content', max_length=5000)),
                ('news_date', models.DateField(help_text='Enter the News date')),
                ('stock_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.stock')),
            ],
        ),
    ]
