# Generated by Django 4.1 on 2022-11-14 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="stocknew", name="news_content",),
        migrations.RemoveField(model_name="stocknew", name="news_title",),
        migrations.AddField(
            model_name="stocknew",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_ticker",
            field=models.CharField(
                help_text="Enter the stock ticker",
                max_length=10,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="threshold",
            name="threshold_percentage_change",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Enter the stock threshold percentage change content",
                max_digits=5,
                null=True,
            ),
        ),
    ]
