# Generated by Django 4.1 on 2022-11-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_stocknew_news_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(help_text='Enter the stock name', max_length=200, null=True),
        ),
    ]
